name: Java Action
on:
  schedule:
    - cron: '0 0 * * 0' # 每周日午夜运行
  push: # 当代码 push 时运行
    branches:
      - main # 只在 main 分支上运行
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install
      - name: Run Java App
        run: java -jar target/github-star-list-1.0.0-jar-with-dependencies.jar
      - name: Commit files
        run: |
          git config --local user.email "mobaijun8@163.com"
          git config --local user.name "mobaijun"
          git pull
          git add Repo.md
          git commit -m ":sparkles: Update Today GitHub Star List Backups"